#define miss_program 0
#define miss_const 1
#define miss_var 2
#define miss_begin 3
#define miss_end 4
#define miss_procedure 5
#define miss_if 6
#define miss_then 7
#define miss_do 8
#define miss_';' 9
#define miss_',' 10
#define miss_')' 11
